# -*- coding: utf-8 -*-
"""Inscription.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YSUNJxLQITzJA6wPRolxyrWhn25S-PxX
"""

logo = """
  _____  _            _      _            _
 |  _  \| | __ _  ___| | __ (_) __ _  ___| | __
 | | /_/| |/ _` |/ __| |/ / | |/ _` |/ __| |/ /
 | |_\ \| | (_| | (__|   <  | | (_| | (__|   <
 |_____/|_|\__,_|\___|_|\_\_| |\__,_|\___|_|\_\\
                          |___|

"""
print(logo)